awslabs/emr-dynamodb-connector

emr-dynamodb-tools/src/main/java/org/apache/hadoop/dynamodb/exportformat/ExportManifestOutputFormat.java
emr-dynamodb-tools/src/main/java/org/apache/hadoop/dynamodb/exportformat/ExportManifestRecordWriter.java
emr-dynamodb-tools/src/main/java/org/apache/hadoop/dynamodb/exportformat/ExportOutputFormat.java
emr-dynamodb-tools/src/main/java/org/apache/hadoop/dynamodb/importformat/ImportRecordReader.java
emr-dynamodb-tools/src/test/java/org/apache/hadoop/dynamodb/exportformat/ExportOutputFormatTest.java

Closes #14 
See #15, this PR incorporates the requested changes, and is rebased onto master.

Support compression codecs in table export.

---

emr-dynamodb-hadoop/src/main/java/org/apache/hadoop/dynamodb/key/DynamoDBBooleanKey.java
emr-dynamodb-hadoop/src/main/java/org/apache/hadoop/dynamodb/type/DynamoDBBooleanType.java
emr-dynamodb-hive/src/main/java/org/apache/hadoop/hive/dynamodb/type/HiveDynamoDBBooleanType.java
emr-dynamodb-hive/src/main/java/org/apache/hadoop/hive/dynamodb/type/HiveDynamoDBTypeFactory.java
emr-dynamodb-hive/src/main/java/org/apache/hadoop/hive/dynamodb/util/DynamoDBDataParser.java

Now you can query boolean datatype from dynamodb

boolean support added

---

emr-dynamodb-hadoop/pom.xml
emr-dynamodb-hive/pom.xml
emr-dynamodb-tools/pom.xml
pom.xml
shims/common/pom.xml
shims/hive1-shims/pom.xml
shims/hive1.2-shims/pom.xml
shims/hive2-shims/pom.xml
shims/loader/pom.xml
shims/pom.xml

% find ./ -iname pom.xml | xargs sed -i -e 's/4.5.0-SNAPSHOT/4.5.0/g'
% mvn clean install
[INFO] Reactor Summary:
[INFO]
[INFO] EMRDynamoDBConnector ............................... SUCCESS [ 0.220 s]
[INFO] EMRDynamoDBHadoop .................................. SUCCESS [01:42 min]
[INFO] EMRDynamoDBConnectorShims .......................... SUCCESS [ 0.003 s]
[INFO] ShimsCommon ........................................ SUCCESS [ 13.681 s]
[INFO] Hive1Shims ......................................... SUCCESS [ 19.825 s]
[INFO] Hive2Shims ......................................... SUCCESS [ 1.715 s]
[INFO] Hive1.2Shims ....................................... SUCCESS [ 12.998 s]
[INFO] ShimsLoader …

Release version 4.5.0

---

emr-dynamodb-hadoop/pom.xml
emr-dynamodb-hive/pom.xml
emr-dynamodb-tools/pom.xml
pom.xml
shims/common/pom.xml
shims/hive1-shims/pom.xml
shims/hive1.2-shims/pom.xml
shims/hive2-shims/pom.xml
shims/loader/pom.xml
shims/pom.xml

% find ./ -iname pom.xml | xargs sed -i -e 's/4.5.0-SNAPSHOT/4.6.0-SNAPSHOT/g'
% mvn clean install 
[INFO] Reactor Summary:
[INFO] 
[INFO] EMRDynamoDBConnector ............................... SUCCESS [  0.286 s]
[INFO] EMRDynamoDBHadoop .................................. SUCCESS [01:17 min]
[INFO] EMRDynamoDBConnectorShims .......................... SUCCESS [  0.004 s]
[INFO] ShimsCommon ........................................ SUCCESS [  0.425 s]
[INFO] Hive1Shims ......................................... SUCCESS [  0.305 s]
[INFO] Hive2Shims ......................................... SUCCESS [  0.144 s]
[INFO] Hive1.2Shims ....................................... SUCCESS [  0.272 s]
[INFO] ShimsLoader …

Prepare for 4.6.0 development

---

emr-dynamodb-hadoop/pom.xml
emr-dynamodb-hive/pom.xml
emr-dynamodb-tools/pom.xml
pom.xml
shims/common/pom.xml
shims/hive1-shims/pom.xml
shims/hive1.2-shims/pom.xml
shims/hive2-shims/pom.xml
shims/loader/pom.xml
shims/pom.xml

```
$ mvn clean versions:set -DnewVersion=4.6.0
$ mvn clean install
[INFO] Reactor Summary:
[INFO]
[INFO] EMRDynamoDBConnector ............................... SUCCESS [  0.424 s]
[INFO] EMRDynamoDBHadoop .................................. SUCCESS [01:21 min]
[INFO] EMRDynamoDBConnectorShims .......................... SUCCESS [  0.010 s]
[INFO] ShimsCommon ........................................ SUCCESS [  1.756 s]
[INFO] Hive1Shims ......................................... SUCCESS [  0.872 s]
[INFO] Hive2Shims ......................................... SUCCESS [  0.565 s]
[INFO] Hive1.2Shims ....................................... SUCCESS [  0.891 s]
[INFO] ShimsLoader ........................................ …
```

Release version 4.6.0

---

emr-dynamodb-hadoop/pom.xml
emr-dynamodb-hive/pom.xml
emr-dynamodb-tools/pom.xml
pom.xml
shims/common/pom.xml
shims/hive1-shims/pom.xml
shims/hive1.2-shims/pom.xml
shims/hive2-shims/pom.xml
shims/loader/pom.xml
shims/pom.xml

```
$ mvn clean versions:set -DnewVersion=4.7.0-SNAPSHOT
$ mvn clean install
[INFO] Reactor Summary:
[INFO]
[INFO] EMRDynamoDBConnector ............................... SUCCESS [  0.442 s]
[INFO] EMRDynamoDBHadoop .................................. SUCCESS [01:18 min]
[INFO] EMRDynamoDBConnectorShims .......................... SUCCESS [  0.021 s]
[INFO] ShimsCommon ........................................ SUCCESS [  1.571 s]
[INFO] Hive1Shims ......................................... SUCCESS [  1.088 s]
[INFO] Hive2Shims ......................................... SUCCESS [  0.544 s]
[INFO] Hive1.2Shims ....................................... SUCCESS [  0.516 s]
[INFO] ShimsLoader …
```

Prepare for 4.7.0 development

---

.gitignore
emr-dynamodb-hadoop/src/main/java/org/apache/hadoop/dynamodb/type/DynamoDBListType.java
emr-dynamodb-hadoop/src/main/java/org/apache/hadoop/dynamodb/type/DynamoDBMapType.java
emr-dynamodb-hadoop/src/test/java/org/apache/hadoop/dynamodb/DynamoDBItemWritableTest.java
emr-dynamodb-hadoop/src/test/java/org/apache/hadoop/dynamodb/test/DynamoDBTestUtils.java
emr-dynamodb-hive/src/main/java/org/apache/hadoop/hive/dynamodb/DerivedHiveTypeConstants.java
emr-dynamodb-hive/src/main/java/org/apache/hadoop/hive/dynamodb/DynamoDBListSerDe.java
emr-dynamodb-hive/src/main/java/org/apache/hadoop/hive/dynamodb/DynamoDBListStorageHandler.java
emr-dynamodb-hive/src/main/java/org/apache/hadoop/hive/dynamodb/DynamoDBSerDe.java
emr-dynamodb-hive/src/main/java/org/apache/hadoop/hive/dynamodb/DynamoDBStorageHandler.java
emr-dynamodb-hive/src/main/java/org/apache/hadoop/hive/dynamodb/type/HiveDynamoDBListType.java
emr-dynamodb-hive/src/main/java/org/apache/hadoop/hive/dynamodb/type/HiveDynamoDBListTypeFactory.java
emr-dynamodb-hive/src/main/java/org/apache/hadoop/hive/dynamodb/type/HiveDynamoDBMapType.java
emr-dynamodb-hive/src/main/java/org/apache/hadoop/hive/dynamodb/type/HiveDynamoDBNumberSetType.java
emr-dynamodb-hive/src/main/java/org/apache/hadoop/hive/dynamodb/type/HiveDynamoDBTypeUtil.java
emr-dynamodb-hive/src/main/java/org/apache/hadoop/hive/dynamodb/util/DynamoDBDataParser.java
emr-dynamodb-hive/src/test/java/org/apache/hadoop/hive/dynamodb/DynamoDBListStorageHandlerTest.java
emr-dynamodb-hive/src/test/java/org/apache/hadoop/hive/dynamodb/DynamoDBStorageHandlerTest.java
emr-dynamodb-hive/src/test/java/org/apache/hadoop/hive/dynamodb/HiveDynamoDBTypeUtilTest.java

I updated the tests, although I don't think any of the classes under /emr-dynamodb-hadoop/src/test/java/org/apache/hadoop/dynamodb/ are covered.

adding list type

---

emr-dynamodb-hadoop/src/main/resources/git.properties
emr-dynamodb-hive/src/main/resources/git.properties
emr-dynamodb-tools/src/main/resources/git.properties
pom.xml
shims/hive1-shims/src/main/resources/git.properties
shims/hive1.2-shims/src/main/resources/git.properties
shims/hive2-shims/src/main/resources/git.properties
shims/loader/src/main/resources/git.properties

This allows validation to ensure the JAR artifacts produced have the most recent commit in a branch.

Add git.properties file

---

emr-dynamodb-hadoop/src/main/java/org/apache/hadoop/dynamodb/preader/RateController.java
emr-dynamodb-hadoop/src/test/java/org/apache/hadoop/dynamodb/preader/RateControllerTest.java

*Issue #, if available:* 94
This limits the possible range of the estimated item size in the RateController to 1B to 400kB as per the DynamoDB limits. Also supports calling adjust() with items = 0 which can happen if an empty result is returned. Previously, if that happened, the avgItemSize would be infinite and the rate limiter would default to RequestLimits with batch size of 1 and wouldn't be able to recover from this

Limit estimated item size to 1-400kB and support empty batches

---

emr-dynamodb-hadoop/src/main/java/org/apache/hadoop/dynamodb/DynamoDBClient.java
emr-dynamodb-hadoop/src/main/java/org/apache/hadoop/dynamodb/DynamoDBConstants.java
emr-dynamodb-hadoop/src/main/java/org/apache/hadoop/dynamodb/write/AbstractDynamoDBRecordWriter.java
emr-dynamodb-hadoop/src/test/java/org/apache/hadoop/dynamodb/DynamoDBClientTest.java

https://github.com/awslabs/emr-dynamodb-connector/issues/70
Adding the ability to delete via the EMR DynamoDB connector

DynamoDB EMR connector deletion

---

emr-dynamodb-hadoop/pom.xml
emr-dynamodb-hive/pom.xml
emr-dynamodb-tools/pom.xml
pom.xml
shims/common/pom.xml
shims/hive1-shims/pom.xml
shims/hive1.2-shims/pom.xml
shims/hive2-shims/pom.xml
shims/loader/pom.xml
shims/pom.xml

Prepare for 4.14.0 release

---

emr-dynamodb-hadoop/pom.xml
emr-dynamodb-hive/pom.xml
emr-dynamodb-tools/pom.xml
pom.xml
shims/common/pom.xml
shims/hive1-shims/pom.xml
shims/hive1.2-shims/pom.xml
shims/hive2-shims/pom.xml
shims/loader/pom.xml
shims/pom.xml

Prepare for 4.15.0 development

Prepare for 4.15.0 development

---

emr-dynamodb-hadoop/pom.xml
emr-dynamodb-hive/pom.xml
emr-dynamodb-tools/pom.xml
pom.xml
shims/common/pom.xml
shims/hive1-shims/pom.xml
shims/hive1.2-shims/pom.xml
shims/hive2-shims/pom.xml
shims/loader/pom.xml
shims/pom.xml

Change development version and JUnit version due to [security advisory](https://github.com/junit-team/junit4/security/advisories/GHSA-269g-pwp5-87pp). 

Prepare for 4.17.0 development

---

emr-dynamodb-hadoop/pom.xml
emr-dynamodb-hadoop/src/main/java/org/apache/hadoop/dynamodb/DynamoDBClient.java
emr-dynamodb-hadoop/src/main/java/org/apache/hadoop/dynamodb/DynamoDBConstants.java
emr-dynamodb-hadoop/src/main/java/org/apache/hadoop/dynamodb/DynamoDBUtil.java
emr-dynamodb-hadoop/src/main/java/org/apache/hadoop/dynamodb/read/AbstractDynamoDBInputFormat.java
emr-dynamodb-hadoop/src/main/java/org/apache/hadoop/dynamodb/split/DynamoDBSegmentsSplit.java
emr-dynamodb-hadoop/src/main/java/org/apache/hadoop/dynamodb/split/DynamoDBSplitGenerator.java
emr-dynamodb-hadoop/src/main/java/org/apache/hadoop/dynamodb/write/WriteIopsCalculator.java
emr-dynamodb-hadoop/src/test/java/org/apache/hadoop/dynamodb/DynamoDBClientTest.java
emr-dynamodb-hadoop/src/test/java/org/apache/hadoop/dynamodb/preader/ReadManagerTest.java
emr-dynamodb-hadoop/src/test/java/org/apache/hadoop/dynamodb/read/DynamoDBRecordReaderTest.java
emr-dynamodb-hadoop/src/test/java/org/apache/hadoop/dynamodb/test/DynamoDBTestUtils.java
emr-dynamodb-hive/pom.xml
emr-dynamodb-hive/src/main/java/org/apache/hadoop/hive/dynamodb/DynamoDBSerDe.java
emr-dynamodb-hive/src/main/java/org/apache/hadoop/hive/dynamodb/DynamoDBStorageHandler.java
emr-dynamodb-hive/src/main/java/org/apache/hadoop/hive/dynamodb/read/HiveDynamoDBInputFormat.java
emr-dynamodb-hive/src/main/java/org/apache/hadoop/hive/dynamodb/split/HiveDynamoDBSegmentsSplit.java
emr-dynamodb-hive/src/main/java/org/apache/hadoop/hive/dynamodb/split/HiveDynamoDBSplitGenerator.java
emr-dynamodb-hive/src/test/java/org/apache/hadoop/hive/dynamodb/DynamoDBSerDeTest.java
pom.xml
shims/hive3-shims/pom.xml
shims/hive3-shims/src/main/java/org/apache/hadoop/hive/dynamodb/shims/DynamoDbHive3Shims.java
shims/hive3-shims/src/main/java/org/apache/hadoop/hive/dynamodb/shims/Hive3SerDeParametersShim.java
shims/loader/pom.xml
shims/loader/src/main/java/org/apache/hadoop/hive/dynamodb/shims/ShimsLoader.java
shims/pom.xml

N/A
Cherry-pick fixes in AWS EMR to benefit broader community. Details can be found in each commit.

Cherry-pick patches from AWS EMR

---

pom.xml

Upgrade `hadoop.version` and `hive3.version` so that all UTs can pass.
```
-------------------------------------------------------
T E S T S
-------------------------------------------------------
Running org.apache.hadoop.dynamodb.write.WriteIopsCalculatorTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.594 sec
Running org.apache.hadoop.dynamodb.split.DynamoDBSplitGeneratorTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.081 sec
Running org.apache.hadoop.dynamodb.DynamoDBUtilTest
Tests run: 11, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.288 sec
Running org.apache.hadoop.dynamodb.test.GsonTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.07 sec
Running …
```

Upgrade Hadoop/Hive versions and fix UT

---

emr-dynamodb-hadoop/pom.xml
emr-dynamodb-hive/pom.xml
emr-dynamodb-tools/pom.xml
pom.xml
shims/common/pom.xml
shims/hive1-shims/pom.xml
shims/hive1.2-shims/pom.xml
shims/hive2-shims/pom.xml
shims/hive3-shims/pom.xml
shims/loader/pom.xml
shims/pom.xml

Update project versions to prepare for 5.0.0-snapshot

Prepare for 5.0.0-snapshot development

---

emr-dynamodb-hadoop/pom.xml
emr-dynamodb-hive/pom.xml
emr-dynamodb-tools/pom.xml
pom.xml
shims/common/pom.xml
shims/hive2-shims/pom.xml
shims/hive3-shims/pom.xml
shims/loader/pom.xml
shims/pom.xml

prepare for 5.2.0-SNAPSHOT development

prepare for 5.2.0-SNAPSHOT development

---

pom.xml

Bump awssdk version up

---

emr-dynamodb-hadoop/pom.xml
emr-dynamodb-hive/pom.xml
emr-dynamodb-tools/pom.xml
pom.xml
shims/common/pom.xml
shims/hive2-shims/pom.xml
shims/hive3-shims/pom.xml
shims/loader/pom.xml
shims/pom.xml

Preparing for 5.5.0-SNAPSHOT development

Preparing for 5.5.0-SNAPSHOT development

---

emr-dynamodb-hadoop/pom.xml
emr-dynamodb-hive/pom.xml
emr-dynamodb-tools/pom.xml
pom.xml
shims/common/pom.xml
shims/hive2-shims/pom.xml
shims/hive3-shims/pom.xml
shims/loader/pom.xml
shims/pom.xml

Preparing for 5.4.0 release

---

emr-dynamodb-hadoop/pom.xml
emr-dynamodb-hive/pom.xml
emr-dynamodb-tools/pom.xml
pom.xml
shims/common/pom.xml
shims/hive2-shims/pom.xml
shims/hive3-shims/pom.xml
shims/loader/pom.xml
shims/pom.xml

N/A
This change is intended to release 5.5.0 for emr-7.3.0.

Prepare for 5.5.0 release

---

emr-dynamodb-hadoop/pom.xml
emr-dynamodb-hive/pom.xml
emr-dynamodb-tools/pom.xml
pom.xml
shims/common/pom.xml
shims/hive2-shims/pom.xml
shims/hive3-shims/pom.xml
shims/loader/pom.xml
shims/pom.xml

N/A
This change is intended to prepare for the next release development (5.6.0-SNAPSHOT) after releasing 5.5.0 for emr-7.3.0.

Prepare for 5.6.0-SNAPSHOT development

---

emr-dynamodb-hadoop/pom.xml
emr-dynamodb-hive/pom.xml
emr-dynamodb-tools/pom.xml
pom.xml
shims/common/pom.xml
shims/hive2-shims/pom.xml
shims/hive3-shims/pom.xml
shims/loader/pom.xml
shims/pom.xml

Prepare for 5.7.0-SNAPSHOT development

Prepare for 5.7.0-SNAPSHOT development

---

emr-dynamodb-hadoop/pom.xml
emr-dynamodb-hive/pom.xml
emr-dynamodb-tools/pom.xml
pom.xml
shims/common/pom.xml
shims/hive2-shims/pom.xml
shims/hive3-shims/pom.xml
shims/loader/pom.xml
shims/pom.xml

Prepare for 5.6.0 release

---

emr-dynamodb-hadoop/pom.xml
emr-dynamodb-hive/pom.xml
emr-dynamodb-tools/pom.xml
pom.xml

Remove relocation logic and set dependency scope to provided for AWS SDK v2 classes.
This allows customers to use public AWS SDKv2 with the connector and provided scope prevents DDB connector jars from causing version conflicts.
Cherry pick of PR - https://github.com/awslabs/emr-dynamodb-connector/pull/212
```
[INFO] Reactor Summary for EMRDynamoDBConnector 5.2.0:
[INFO] 
[INFO] EMRDynamoDBConnector ............................... SUCCESS [  0.414 s]
[INFO] EMRDynamoDBHadoop .................................. SUCCESS [01:07 …
```

Remove shading and relocation for AWS SDKv2 dependencies

---

README.md

* Updated Readme to clarify that the connector is not supported by EMR Serverless. 

Added EMR Serverless related information to README.md

---

emr-dynamodb-hadoop/pom.xml
emr-dynamodb-hive/pom.xml
emr-dynamodb-tools/pom.xml
pom.xml
shims/common/pom.xml
shims/hive2-shims/pom.xml
shims/hive3-shims/pom.xml
shims/loader/pom.xml
shims/pom.xml

Preparation for 5.8.0-SNAPSHOT development after 5.7.0 release branch cut

Prepare for 5.8.0-SNAPSHOT development
