emr-dynamodb-hadoop/src/main/java/org/apache/hadoop/dynamodb/preader/AbstractRecordReadRequest.java
emr-dynamodb-hadoop/src/main/java/org/apache/hadoop/dynamodb/preader/PageResults.java
emr-dynamodb-hadoop/src/test/java/org/apache/hadoop/dynamodb/read/DynamoDBRecordReaderTest.java

When reads fail constantly for a particular page (number of retry exceeds) the exception will be logged and the page and whole segment will be discarded. As a result ReadWorker will loop forever waiting for the missing segment.

Implement proper Exception handling in DynamoDb connector ScanRecordReadRequest

---

emr-dynamodb-hive/pom.xml
emr-dynamodb-hive/src/main/java/org/apache/hadoop/hive/dynamodb/DynamoDBExportSerDe.java
emr-dynamodb-hive/src/main/java/org/apache/hadoop/hive/dynamodb/DynamoDBSerDe.java
pom.xml
shims/common/src/main/java/org/apache/hadoop/hive/dynamodb/shims/DynamoDbHiveShims.java
shims/common/src/main/java/org/apache/hadoop/hive/dynamodb/shims/SerDeParametersShim.java
shims/hive1-shims/pom.xml
shims/hive1-shims/src/main/java/org/apache/hadoop/hive/dynamodb/shims/DynamoDbHive1Shims.java
shims/hive1-shims/src/main/java/org/apache/hadoop/hive/dynamodb/shims/Hive1SerDeParametersShim.java
shims/hive1.2-shims/pom.xml
shims/hive1.2-shims/src/main/java/org/apache/hadoop/hive/dynamodb/shims/DynamoDbHive1Dot2Shims.java
shims/hive2-shims/src/main/java/org/apache/hadoop/hive/dynamodb/shims/DynamoDbHive2Shims.java
shims/hive2-shims/src/main/java/org/apache/hadoop/hive/dynamodb/shims/Hive2SerDeParametersShim.java
shims/loader/pom.xml
shims/loader/src/main/java/org/apache/hadoop/hive/dynamodb/shims/ShimsLoader.java
shims/loader/test/main/java/org/apache/hadoop/hive/dynamodb/shims/ShimsLoaderTest.java
shims/pom.xml

Originally the Shim layer consisted of only two method calls which
differed between hive 1.x and hive 2.x. Unfortunately, Hive 1.2.x
makes use of the LazySerDeParameters constructor as opposed to the
"older" LazySimpleSerDe.initSerdeParams() static factory method.
This change introduces a SerDeParameterShim class to help delegate
this usage depending on the detected runtime Hive version, and
utilizes the original shim logic to do so.

Add shim for Hive 1.2.x compatability

---

README.md
emr-dynamodb-hadoop/pom.xml
emr-dynamodb-hive/pom.xml
emr-dynamodb-tools/pom.xml
pom.xml
shims/common/pom.xml
shims/hive1.2-shims/pom.xml

hadoop-common and hive-exec transitively depend on old versions
of Jackson libraries, which cause runtime errors when using Hive
on Tez. The Maven DependencyManagement mechanism was used to
achieve this. This change also updates a few outdated points
and typos in the README.

Make all dependencies on Hive and Hadoop 'provided' scope

---

emr-dynamodb-hive/pom.xml

Hive 1.0.0 doesn't bring in some classes that are normally
brought in when building against Hive 1.2.1 or Hive 2.0.0.
This change returns hadoop-common to the project-default
'provided' scope in order to allow building against Hive
1.0.0 to work correctly.

Make Hadoop 'provided' to support Hive 1.0.0

---

emr-dynamodb-hadoop/src/main/java/org/apache/hadoop/dynamodb/DynamoDBItemWritable.java

This fixes: https://github.com/awslabs/emr-dynamodb-connector/issues/13
This patch makes DynamoDBItemWritable implement Serializable because pyspark requires that a writeObject implements Serializable [1].
[1] https://github.com/apache/spark/blob/v2.1.0/core/src/main/scala/org/apache/spark/serializer/JavaSerializer.scala#L45

Make DynamoDBItemWritable implement Serializable

---

emr-dynamodb-hadoop/src/main/java/org/apache/hadoop/dynamodb/preader/ScanRecordReadRequest.java
emr-dynamodb-hadoop/src/test/java/org/apache/hadoop/dynamodb/preader/ScanRecordReadRequestTest.java

Per http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBLocal.UsageNotes.html
ScanResult#getConsumedCapacity() returns null for operation
responses against a DynamoDBLocal instance. This was resulting in NPEs
for users developing against a local instance.
This fixes: https://github.com/awslabs/emr-dynamodb-connector/issues/11

Null check ScanResult#getConsumedCapacity()

---

pom.xml

This change upgrades the AWS Java SDK, as well as adds an exclude
to the hadoop-common dependency to leave out an older version
(4.1.2) of the org.apache.httpcomponents artifacts: httpclient
and httpcore. This was causing a conflict while fixing another
issue.

Bump AWS SDK from 1.10.66 to 1.10.77 and exclude httpcomponents

---

emr-dynamodb-hadoop/src/main/java/org/apache/hadoop/dynamodb/DynamoDBClient.java
emr-dynamodb-hadoop/src/main/java/org/apache/hadoop/dynamodb/DynamoDBConstants.java
emr-dynamodb-hadoop/src/main/java/org/apache/hadoop/dynamodb/DynamoDBUtil.java
emr-dynamodb-hadoop/src/test/java/org/apache/hadoop/dynamodb/DynamoDBClientTest.java
emr-dynamodb-hadoop/src/test/java/org/apache/hadoop/dynamodb/DynamoDBUtilTest.java

The DynamoDB client has historically been using only a single constant to
limit the maximum size of an item that can be stored in DynamoDB using the
connector. This is incorrect/inefficient as it doesn't truly reflect the
limits imposed by the DynamoDB service.
DynamoDB enforces two separate limits:
1. A single item cannot exceed 400KB
2. An entire request in a Batch(Get/Write)Item request/response cannot
exceed 16MB
This change splits up the original logic to ensure that each of these
limits are enforced separately, and ensures that batch writes in particular
aren't capped at 512KB as they have been originally.
This change also makes three different values configurable:
1. Max item size: "dynamodb.item.max.size" (default: 400KB)
2. Max batch request/response size: …

Split up max item/batch sizes & make them configurable

---

README.md
emr-dynamodb-hadoop/src/main/java/org/apache/hadoop/dynamodb/util/ClusterTopologyNodeCapacityProvider.java
pom.xml

Modifies ClusterTopologyNodeCapacityProvider to use Jackson instead of deprecated json.org in 1.11.x of the AWS Java SDK.

Bump AWS Java SDK to 1.11.129, Hadoop to 2.7.3, and Hive2 to 2.1.1.

---

README.md
emr-dynamodb-hive/src/main/java/org/apache/hadoop/hive/dynamodb/DynamoDBExportSerDe.java
emr-dynamodb-hive/src/main/java/org/apache/hadoop/hive/dynamodb/DynamoDBSerDe.java
emr-dynamodb-hive/src/main/java/org/apache/hadoop/hive/dynamodb/DynamoDBStorageHandler.java
pom.xml
shims/hive2-shims/src/main/java/org/apache/hadoop/hive/dynamodb/shims/DynamoDbHive2Shims.java

The SerDe interface was removed in Hive 2.3.0: https://issues.apache.org/jira/browse/HIVE-15167
This changes all instances of 'SerDe' to 'AbstractSerDe' to address.
Also update pom and Hive2Shims to reflect updated versions of Hive and AWS Java SDK.

Fix compatibility with Hive 2.3.0

---

emr-dynamodb-hadoop/src/main/java/org/apache/hadoop/dynamodb/write/AbstractDynamoDBRecordWriter.java

Existing code assumes a response from DynamoDB includes a "consumed capacity" property (since it's requested).  However, it appears that the local (non-hosted) version of DynamoDB which is made available for testing purposes does not return the property, even when requested.  As such, a NPE can occur here.
This will likely affect the function of the IOPSController, since we cannot update the consumed units, but I suspect it doesn't matter in the local DynamoDB case, since there are no actual capacity controls.

Null check on result.getConsumedCapacity()

---

README.md

Line breaks inbetween the link text and the actual URL tag will cause the
link to not render correctly on GitHub.

Fix markdown links for GitHub README page.

---

emr-dynamodb-hadoop/src/main/java/org/apache/hadoop/dynamodb/DynamoDBItemWritable.java
emr-dynamodb-hadoop/src/main/java/org/apache/hadoop/dynamodb/read/AbstractDynamoDBRecordReader.java
emr-dynamodb-hadoop/src/test/java/org/apache/hadoop/dynamodb/DynamoDBItemWritableTest.java
emr-dynamodb-hive/src/main/java/org/apache/hadoop/hive/dynamodb/DynamoDBExportSerDe.java
emr-dynamodb-hive/src/main/java/org/apache/hadoop/hive/dynamodb/DynamoDBSerDe.java

Added a constructor to take dynamoDBItemMap as an argument. Refactored the code to create dynamoDBItemMap(HashMap) only when initialized with no args constructor.
This pull request is pretty simple and not related to any issue, but can be useful for the users.
Attached Tests Snippet
[test_snippet.txt](https://github.com/awslabs/emr-dynamodb-connector/files/2313921/test_snippet.txt)

Add parametrized constructor for DynamoDBItemWritable

---

emr-dynamodb-hadoop/src/main/java/org/apache/hadoop/dynamodb/read/ReadIopsCalculator.java
emr-dynamodb-hadoop/src/main/java/org/apache/hadoop/dynamodb/write/WriteIopsCalculator.java
emr-dynamodb-hive/src/main/java/org/apache/hadoop/hive/dynamodb/DynamoDBSerDe.java
emr-dynamodb-hive/src/main/java/org/apache/hadoop/hive/dynamodb/DynamoDBStorageHandler.java
emr-dynamodb-tools/src/main/java/org/apache/hadoop/dynamodb/tools/DynamoDBExport.java
emr-dynamodb-tools/src/main/java/org/apache/hadoop/dynamodb/tools/DynamoDBImport.java

- billingModeSummary can be null on new provisioned mode tables
Bug was introduced in this PR https://github.com/awslabs/emr-dynamodb-connector/commit/dca6c7547c446e33aff25da7fdf7d15c10aef516 (if you look at that PR you'll see a similar null check in other places)

Fixing NullPointerException for provisioned mode tables

---

emr-dynamodb-hive/src/main/java/org/apache/hadoop/hive/dynamodb/DynamoDBStorageHandler.java

Auto scale in provisioned billing mode if user hasn't explicitly specify throughput.
*Issue : https://github.com/awslabs/emr-dynamodb-connector/issues/99*
Auto scaling in provisioned mode was working in previous version, but has been suppressed in [commit](https://github.com/awslabs/emr-dynamodb-connector/commit/dca6c7547c446e33aff25da7fdf7d15c10aef516#diff-9ac2a3ee2c139328fd4a0076417da17aL70). 
This commit is trying to resolve this issue by do not set READ/WRITE_THROUGHPUT if user did not explicitly set it in table description. Then IopsCalculator will get latest provisioned capacity periodically. 
It'll respect user's explicit set READ/WRITE_THROUGHPUT if there's any.
It keeps current behavior if table's billing mode is ON_DEMAND. 
Related changes are: 
* When …

Auto scale in provisioned billing mode if user hasn't explicitly specify throughput

---

emr-dynamodb-hadoop/src/main/java/org/apache/hadoop/dynamodb/DynamoDBUtil.java
emr-dynamodb-hadoop/src/test/java/org/apache/hadoop/dynamodb/DynamoDBUtilTest.java
emr-dynamodb-hive/src/main/java/org/apache/hadoop/hive/dynamodb/DynamoDBStorageHandler.java
emr-dynamodb-hive/src/test/java/org/apache/hadoop/hive/dynamodb/DynamoDBStorageHandlerTest.java

1. Throw an exception if the mapping between Hive schema columns and
keys in dynamodb.column.mapping is not 1:1.
2. Allow for null (0-byte) DynamoDB items.
Issue #74

Fix exception thrown for bad mapping

---

emr-dynamodb-hive/src/main/java/org/apache/hadoop/hive/dynamodb/DerivedHiveTypeConstants.java
emr-dynamodb-hive/src/main/java/org/apache/hadoop/hive/dynamodb/DynamoDBExportSerDe.java
emr-dynamodb-hive/src/main/java/org/apache/hadoop/hive/dynamodb/DynamoDBListObjectInspector.java
emr-dynamodb-hive/src/main/java/org/apache/hadoop/hive/dynamodb/DynamoDBListSerDe.java
emr-dynamodb-hive/src/main/java/org/apache/hadoop/hive/dynamodb/DynamoDBObjectInspector.java
emr-dynamodb-hive/src/main/java/org/apache/hadoop/hive/dynamodb/DynamoDBSerDe.java
emr-dynamodb-hive/src/main/java/org/apache/hadoop/hive/dynamodb/DynamoDBStorageHandler.java
emr-dynamodb-hive/src/main/java/org/apache/hadoop/hive/dynamodb/type/HiveDynamoDBBinarySetType.java
emr-dynamodb-hive/src/main/java/org/apache/hadoop/hive/dynamodb/type/HiveDynamoDBBinaryType.java
emr-dynamodb-hive/src/main/java/org/apache/hadoop/hive/dynamodb/type/HiveDynamoDBBooleanType.java
emr-dynamodb-hive/src/main/java/org/apache/hadoop/hive/dynamodb/type/HiveDynamoDBListType.java
emr-dynamodb-hive/src/main/java/org/apache/hadoop/hive/dynamodb/type/HiveDynamoDBListTypeFactory.java
emr-dynamodb-hive/src/main/java/org/apache/hadoop/hive/dynamodb/type/HiveDynamoDBMapType.java
emr-dynamodb-hive/src/main/java/org/apache/hadoop/hive/dynamodb/type/HiveDynamoDBNumberSetType.java
emr-dynamodb-hive/src/main/java/org/apache/hadoop/hive/dynamodb/type/HiveDynamoDBNumberType.java
emr-dynamodb-hive/src/main/java/org/apache/hadoop/hive/dynamodb/type/HiveDynamoDBStringSetType.java
emr-dynamodb-hive/src/main/java/org/apache/hadoop/hive/dynamodb/type/HiveDynamoDBStringType.java
emr-dynamodb-hive/src/main/java/org/apache/hadoop/hive/dynamodb/type/HiveDynamoDBTypeFactory.java
emr-dynamodb-hive/src/main/java/org/apache/hadoop/hive/dynamodb/util/DynamoDBDataParser.java
emr-dynamodb-hive/src/test/java/org/apache/hadoop/hive/dynamodb/HiveDynamoDBTypeUtilTest.java

Issue #82 : Currently, DynamoDB lists show up as `null` in Hive tables due to issues in parsing logic.
The following changes fix these issues so that the connector can properly support DynamoDB lists, including nested lists:
1. Include alternate `DynamoDBListObjectInspector` to map arrays to lists.
2. Infer element type of list and use element type object to parse elements when serializing and deserializing.

Fix parsing logic for List type

---

README.md
emr-dynamodb-hive/src/main/java/org/apache/hadoop/hive/dynamodb/type/HiveDynamoDBMapType.java
emr-dynamodb-hive/src/main/java/org/apache/hadoop/hive/dynamodb/util/DynamoDBDataParser.java
emr-dynamodb-hive/src/test/java/org/apache/hadoop/hive/dynamodb/DynamoDBObjectInspectorTest.java
emr-dynamodb-hive/src/test/java/org/apache/hadoop/hive/dynamodb/DynamoDBSerDeTest.java
emr-dynamodb-hive/src/test/java/org/apache/hadoop/hive/dynamodb/DynamoDBStorageHandlerTest.java
emr-dynamodb-hive/src/test/java/org/apache/hadoop/hive/dynamodb/type/HiveDynamoDBTypeTest.java

Add support for users to read or write Hive structs as DynamoDB maps.

Add support for Hive structs

---

README.md
emr-dynamodb-hadoop/src/main/java/org/apache/hadoop/dynamodb/DynamoDBConstants.java
emr-dynamodb-hadoop/src/main/java/org/apache/hadoop/dynamodb/type/DynamoDBNullType.java
emr-dynamodb-hadoop/src/main/java/org/apache/hadoop/dynamodb/type/DynamoDBTypeConstants.java
emr-dynamodb-hive/src/main/java/org/apache/hadoop/hive/dynamodb/DynamoDBSerDe.java
emr-dynamodb-hive/src/main/java/org/apache/hadoop/hive/dynamodb/DynamoDBStorageHandler.java
emr-dynamodb-hive/src/main/java/org/apache/hadoop/hive/dynamodb/type/HiveDynamoDBBinarySetType.java
emr-dynamodb-hive/src/main/java/org/apache/hadoop/hive/dynamodb/type/HiveDynamoDBBinaryType.java
emr-dynamodb-hive/src/main/java/org/apache/hadoop/hive/dynamodb/type/HiveDynamoDBItemType.java
emr-dynamodb-hive/src/main/java/org/apache/hadoop/hive/dynamodb/type/HiveDynamoDBListType.java
emr-dynamodb-hive/src/main/java/org/apache/hadoop/hive/dynamodb/type/HiveDynamoDBMapType.java
emr-dynamodb-hive/src/main/java/org/apache/hadoop/hive/dynamodb/type/HiveDynamoDBNullType.java
emr-dynamodb-hive/src/main/java/org/apache/hadoop/hive/dynamodb/type/HiveDynamoDBNumberSetType.java
emr-dynamodb-hive/src/main/java/org/apache/hadoop/hive/dynamodb/type/HiveDynamoDBNumberType.java
emr-dynamodb-hive/src/main/java/org/apache/hadoop/hive/dynamodb/type/HiveDynamoDBStringSetType.java
emr-dynamodb-hive/src/main/java/org/apache/hadoop/hive/dynamodb/type/HiveDynamoDBStringType.java
emr-dynamodb-hive/src/main/java/org/apache/hadoop/hive/dynamodb/type/HiveDynamoDBType.java
emr-dynamodb-hive/src/main/java/org/apache/hadoop/hive/dynamodb/type/HiveDynamoDBTypeFactory.java
emr-dynamodb-hive/src/main/java/org/apache/hadoop/hive/dynamodb/util/DynamoDBDataParser.java
emr-dynamodb-hive/src/main/java/org/apache/hadoop/hive/dynamodb/util/HiveDynamoDBUtil.java
emr-dynamodb-hive/src/test/java/org/apache/hadoop/hive/dynamodb/DynamoDBObjectInspectorTest.java
emr-dynamodb-hive/src/test/java/org/apache/hadoop/hive/dynamodb/DynamoDBSerDeTest.java
emr-dynamodb-hive/src/test/java/org/apache/hadoop/hive/dynamodb/DynamoDBStorageHandlerTest.java
emr-dynamodb-hive/src/test/java/org/apache/hadoop/hive/dynamodb/type/HiveDynamoDBTypeTest.java

Add option for serializing Hive null values (including those within collections) to DynamoDB null type if `"dynamodb.null.serialiation" = "true"` is specified.

Add support for DynamoDB null type

---

emr-dynamodb-hadoop/src/main/java/org/apache/hadoop/dynamodb/CredentialPairName.java
emr-dynamodb-hadoop/src/main/java/org/apache/hadoop/dynamodb/DynamoDBClient.java
emr-dynamodb-hadoop/src/main/java/org/apache/hadoop/dynamodb/DynamoDBConstants.java
emr-dynamodb-hadoop/src/test/java/org/apache/hadoop/dynamodb/DynamoDBClientTest.java

#75 
To support cross-account DynamoDB access using STS  instead of using static access keys.
Added new property **dynamodb.awsSessionToken** to pass the session key
*Sample invocation :*
` 
hadoop jar target/emr-dynamodb-tools-4.10.0-SNAPSHOT.jar org.apache.hadoop.dynamodb.tools.DynamoDBExport -Ddynamodb.awsSessionToken=${SESSION_TOKEN} -Ddynamodb.awsAccessKeyId=${ACCESS_KEY_ID} -Ddynamodb.awsSecretAccessKey=${SECRET_ACCESS_KEY}
/where/output/should/go my-dynamo-table-name
`
Attached Tests Results:
[sts_tests.log](https://github.com/awslabs/emr-dynamodb-connector/files/3281139/sts_tests.log)

Added support for using STS session credentials

---

emr-dynamodb-hadoop/src/main/java/org/apache/hadoop/dynamodb/DynamoDBClient.java
emr-dynamodb-hadoop/src/main/java/org/apache/hadoop/dynamodb/preader/ScanRecordReadRequest.java
emr-dynamodb-hadoop/src/test/java/org/apache/hadoop/dynamodb/preader/ScanRecordReadRequestTest.java
emr-dynamodb-hadoop/src/test/java/org/apache/hadoop/dynamodb/read/DynamoDBRecordReaderTest.java

Adding support to select only required fields while scanning DynamoDB table to reduce the amount of data transferred.

Add support for projections for DynamoDB table scan spark jobs

---

pom.xml

Upgrade Java version to 1.8 & upgrade Guava version due to the security issue of Guava
*Description of changes:
According to the github security alert, we need to upgrade ```com.google.guava:guava``` to version 24.1.1 or later.
Github Dependabot shows that Dependabot cannot update to the required version so we need to manually update Guava version.
Since ```guava 24.1.1``` depends on ```Java 1.8```, I also upgraded Java from 1.7 to 1.8 at the same time.

Upgrade Java version to 1.8 & upgrade Guava version

---

README.md
emr-dynamodb-hadoop/src/main/java/org/apache/hadoop/dynamodb/DynamoDBClient.java
emr-dynamodb-hadoop/src/main/java/org/apache/hadoop/dynamodb/filter/DynamoDBIndexInfo.java
emr-dynamodb-hadoop/src/main/java/org/apache/hadoop/dynamodb/filter/DynamoDBQueryFilter.java
emr-dynamodb-hive/src/main/java/org/apache/hadoop/hive/dynamodb/filter/DynamoDBFilterPushdown.java
emr-dynamodb-hive/src/main/java/org/apache/hadoop/hive/dynamodb/read/HiveDynamoDBInputFormat.java
emr-dynamodb-hive/src/test/java/org/apache/hadoop/hive/dynamodb/filter/DynamoDBFilterPushdownTest.java

https://github.com/awslabs/emr-dynamodb-connector/issues/87
https://github.com/awslabs/emr-dynamodb-connector/issues/102
* Check LSIs and GSIs for optimal pushdown key conditions if not both hash key and range key for the DynamoDB table are found in query predicate
* Pull analyzer initialization outside methods
* Update pushdown eligibleHiveType to include binary type since it is also allowed for primary key attributes according to [Amazon DynamoDB doc](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/HowItWorks.CoreComponents.html#HowItWorks.CoreComponents.PrimaryKey)
* Add unit tests for DynamoDBFilterPushdown.java
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this …

Add GSI/LSI pushdown support for Hive

---

shims/loader/pom.xml
shims/loader/src/main/java/org/apache/hadoop/hive/dynamodb/shims/ShimsLoader.java
shims/loader/test/main/java/org/apache/hadoop/hive/dynamodb/shims/ShimsLoaderTest.java
shims/pom.xml

This commit targets to remove support for Hive 1.x since EMR doesn't support Hive 1.x anymore.

Remove Hive 1.x support

---

emr-dynamodb-hadoop/pom.xml
emr-dynamodb-hive/pom.xml
pom.xml

In #175, we upgrade AWS SDK V1 to AWS SDK V2. In addition, we bundle the AWS SDK V2 dependency into the JAR.
This will cause dependency conflict when customer app is depending on another version of AWS SDK V2 and running   in the same JVM. 
In this PR, we shade and relocate AWS SDK V2 to a different namespace so there won't be any conflict with customer app's own dependency to other versions of AWS SDK V2.

Shade and relocate AWS SDK V2 dependency

---

shims/hive2-shims/pom.xml

This closes #184.
`org.pentaho:pentaho-aggdesigner-algorithm:jar:5.1.5-jhyde` is not available in Maven repo and this change excludes the dependency.

Fix mvn install

---

emr-dynamodb-hadoop/src/main/java/org/apache/hadoop/dynamodb/DynamoDBClient.java
emr-dynamodb-hadoop/src/main/java/org/apache/hadoop/dynamodb/DynamoDBUtil.java
emr-dynamodb-hadoop/src/main/java/org/apache/hadoop/dynamodb/util/DynamoDBReflectionUtils.java
emr-dynamodb-hadoop/src/test/java/org/apache/hadoop/dynamodb/DynamoDBClientTest.java

N/A
DynamoDB connector uses reflection to load custom credential providers. When the package was upgraded to use aws-java-sdk-v2, the package was only updated to fix the differing classpaths. SDK-v2 credential providers no longer use constructors but static create() methods to initialize the instance which was not handled in the previous implementation. This PR accounts for this use case and includes a fallback to the original logic to ensure backwards compatibility.
*Testing done:*
```
[INFO] Reactor Summary for EMRDynamoDBConnector 5.5.0-SNAPSHOT:
[INFO]
[INFO] EMRDynamoDBConnector ............................... SUCCESS [  0.258 s]
[INFO] …
```

Fix reflection logic of aws-java-sdk-v2 credential providers

---

emr-dynamodb-hadoop/src/main/java/org/apache/hadoop/dynamodb/DynamoDBClient.java
emr-dynamodb-hadoop/src/test/java/org/apache/hadoop/dynamodb/DynamoDBClientTest.java

The default credential provider dynamodb connector falls back to is InstanceProfileCredentialProvider. However, the instance profile is not available in all deployment environments (e.g. EMR Serverless). Instead, aws-java-sdk-v2's default provider should be used as the fallback to handle all environments. This keeps existing behavior as InstanceProfile provider is last provider in the default chain but also contains required providers for other deployments.
N/A
See above
*Testing*
mvn clean install:
```
[INFO] Reactor Summary for EMRDynamoDBConnector 5.5.0-SNAPSHOT:
[INFO]
[INFO] EMRDynamoDBConnector ............................... SUCCESS [  0.309 s]
[INFO] …
```

Set default credential provider to sdk's default provider

---

emr-dynamodb-hadoop/src/main/java/org/apache/hadoop/dynamodb/DynamoDBClient.java
emr-dynamodb-hadoop/src/main/java/org/apache/hadoop/dynamodb/DynamoDBUtil.java
emr-dynamodb-hadoop/src/main/java/org/apache/hadoop/dynamodb/util/DynamoDBReflectionUtils.java
emr-dynamodb-hadoop/src/test/java/org/apache/hadoop/dynamodb/DynamoDBClientTest.java

This is a backport/cherry pick of issues:
https://github.com/awslabs/emr-dynamodb-connector/pull/201
https://github.com/awslabs/emr-dynamodb-connector/pull/203
View above for more information about the change
*Testing*
```
[INFO] Reactor Summary for EMRDynamoDBConnector 5.3.0:
[INFO]
[INFO] EMRDynamoDBConnector ............................... SUCCESS [  0.353 s]
[INFO] EMRDynamoDBHadoop .................................. SUCCESS [01:07 min]
[INFO] EMRDynamoDBConnectorShims .......................... SUCCESS [  0.006 s]
[INFO] ShimsCommon ........................................ SUCCESS [  0.554 s]
[INFO] Hive2Shims ......................................... SUCCESS [ …
```

Backport DDB connector Credential Provider Fix EMR 7.1.0

---

emr-dynamodb-hadoop/src/main/java/org/apache/hadoop/dynamodb/DynamoDBClient.java
emr-dynamodb-hadoop/src/main/java/org/apache/hadoop/dynamodb/DynamoDBUtil.java
emr-dynamodb-hadoop/src/main/java/org/apache/hadoop/dynamodb/util/DynamoDBReflectionUtils.java
emr-dynamodb-hadoop/src/test/java/org/apache/hadoop/dynamodb/DynamoDBClientTest.java

This is a backport/cherry pick of issues:
https://github.com/awslabs/emr-dynamodb-connector/pull/201
https://github.com/awslabs/emr-dynamodb-connector/pull/203
View above for more information about the change
*Testing*
```
[INFO] Reactor Summary for EMRDynamoDBConnector 5.4.0:
[INFO]
[INFO] EMRDynamoDBConnector ............................... SUCCESS [  0.313 s]
[INFO] EMRDynamoDBHadoop .................................. SUCCESS [01:08 min]
[INFO] EMRDynamoDBConnectorShims .......................... SUCCESS [  0.004 s]
[INFO] ShimsCommon ........................................ SUCCESS [  0.590 s]
[INFO] Hive2Shims ......................................... SUCCESS [ …
```

Backport DDB connector Credential Provider Fix  for v5.4.0

---

emr-dynamodb-hadoop/pom.xml
emr-dynamodb-hive/pom.xml
emr-dynamodb-tools/pom.xml
pom.xml

Remove relocation logic and set dependency scope to provided for AWS SDK v2 classes.
This allows customers to use public AWS SDKv2 with the connector and provided scope prevents DDB connector jars from causing version conflicts.
Cherry pick of PR - https://github.com/awslabs/emr-dynamodb-connector/pull/212
```
[INFO] Reactor Summary for EMRDynamoDBConnector 5.5.0:
[INFO] 
[INFO] EMRDynamoDBConnector ............................... SUCCESS [  0.441 s]
[INFO] EMRDynamoDBHadoop .................................. SUCCESS [01:05 …
```

Remove shading and relocation for AWS SDKv2 dependencies

---

README.md

The customers can access dynamo db with EMR Serverless now, see this [doc](https://docs.aws.amazon.com/emr/latest/EMR-Serverless-UserGuide/using-ddb-connector.html).
Remove the outdated information and add EMR Serverless User Guide to README.md

Add updated EMR Serverless User Guide to README.md
